# PRODUCTS_COLLECTION = "products"
# STORES_COLLECTION = "stores"
# INVENTORY_COLLECTION = "inventory_current"

PRODUCTS_COLLECTION = "products"
STORES_COLLECTION = "stores"
INVENTORY_COLLECTION = "inventory_current"
STORE_DISTANCES_COLLECTION = "store_distances"

ANALYTICS_SUMMARY_COLLECTION = "analytics_summary"
SHOWROOM_ANALYTICS_COLLECTION = "showroom_analytics"
CATEGORY_ANALYTICS_COLLECTION = "category_analytics"
BRAND_ANALYTICS_COLLECTION = "brand_analytics"
GENDER_ANALYTICS_COLLECTION = "gender_analytics"
ALERT_ITEMS_COLLECTION = "alert_items"

OPTIMIZATION_CANDIDATES_COLLECTION = "optimization_candidates"
OPTIMIZATION_HISTORY_COLLECTION = "optimization_history"
STOCK_MOVEMENTS_COLLECTION = "stock_movements"
INVENTORY_TRANSACTIONS_COLLECTION = "inventory_transactions"
MANAGER_CHAT_SESSIONS_COLLECTION = "manager_chat_sessions"
MANAGER_CHAT_MESSAGES_SUBCOLLECTION = "messages"

MONTHLY_FORECAST_PROFILES_COLLECTION = "monthly_forecast_profiles"

DECISION_WORKFLOWS_COLLECTION = "decision_workflows"

MARKETING_OPPORTUNITIES_COLLECTION = "marketing_opportunities"
